### ISSUE TITLE
providers not up to date?

### ISSUE THREAD

**Issue by ltalirz** [CasperWA/voila-optimade-client#33] opened 2020-05-12 06:37 UTC
The FAQ seems to imply that providers are fetched from the optimade index DB but a couple of them seem to be missing (e.g. COD)

https://github.com/Materials-Consortia/providers/blob/master/src/links/v1/providers.json

I also notice that e.g. the materials project and nomad have empty base urls despite the fact that they should already have working implementations (?). Perhaps you could ping them?

**Comment by CasperWA** [comment] 2020-05-12 08:56
Please see the FAQ for answers to your question.
Specifically for COD, the issue is that their implementation is not up-to-date in any shape or form, hence it is being filtered out. This is done in the client, in order to only include providers that can actually be handled.

Currently there is a PR open to add Materials Project (Materials-Consortia/providers#23). The other honorable mentions are pinged regularly at consortium meetings.

Closing this.
If you do not think I have answered your questions or that the FAQ needs to be extended / perfected, please either raise a new issue concerning this or open a PR 👍 😃

**Closed as completed by CasperWA** 2020-05-12 08:56 UTC

**Comment by ltalirz** [comment] 2020-05-12 09:30
Ok, thanks for the clarification. Let's hope a few more providers will come online soon! :-)
