### ISSUE TITLE
[BUG] - Searching MaterialsProject with provider id results in error

### ISSUE THREAD

**Issue by csadorf** [CasperWA/voila-optimade-client#208] opened 2020-11-05 08:55 UTC
## Bug description

I tried to search the MaterialsProject DB with a provider ID and the search fails with the following error:
![Screen Shot 2020-11-05 at 9 53 58 AM](https://user-images.githubusercontent.com/1441208/98219155-f1d25100-1f4c-11eb-90fe-c20d2183dbba.png)

### For developers (do not alter this section)
<details>
  <summary>Log dump</summary>

  ```
  ...
  [ERROR 08:53:54 utils.py:503] Errored response:
{
  "meta": {
    "query": {
      "representation": "/structures?filter=%28+id%3Dmp-19017+%29+AND+%28+NOT+structure_features+HAS+ANY+%22assemblies%22+%29&response_format=json&page_limit=10&page_offset=0&page_number=1"
    },
    "api_version": "1.0.0",
    "more_data_available": false,
    "time_stamp": "2020-11-05T08:53:54Z",
    "data_returned": 0,
    "provider": {
      "name": "The Materials Project",
      "description": "The Materials Project OPTIMADE endpoint",
      "prefix": "mp",
      "homepage": "https://materialsproject.org"
    },
    "data_available": 0,
    "implementation": {
      "name": "OPTIMADE Python Tools",
      "version": "0.12.1",
      "homepage": null,
      "source_url": "https://github.com/Materials-Consortia/optimade-python-tools",
      "maintainer": {
        "email": "dev@optimade.org"
      }
    },
    "_mp_traceback": "Traceback (most recent call last):\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/errors.py\", line 159, in __call__\n    await self.app(scope, receive, _send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 25, in __call__\n    response = await self.dispatch_func(request, self.call_next)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/middleware.py\", line 424, in dispatch\n    response = await call_next(request)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 45, in call_next\n    task.result()\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 38, in coro\n    await self.app(scope, receive, send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 25, in __call__\n    response = await self.dispatch_func(request, self.call_next)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/middleware.py\", line 273, in dispatch\n    response = await call_next(request)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 45, in call_next\n    task.result()\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 38, in coro\n    await self.app(scope, receive, send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 25, in __call__\n    response = await self.dispatch_func(request, self.call_next)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/middleware.py\", line 112, in dispatch\n    response = await call_next(request)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 45, in call_next\n    task.result()\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 38, in coro\n    await self.app(scope, receive, send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 25, in __call__\n    response = await self.dispatch_func(request, self.call_next)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/middleware.py\", line 74, in dispatch\n    response = await call_next(request)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 45, in call_next\n    task.result()\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/base.py\", line 38, in coro\n    await self.app(scope, receive, send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/middleware/cors.py\", line 78, in __call__\n    await self.app(scope, receive, send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/exceptions.py\", line 82, in __call__\n    raise exc from None\n  File \"/root/.local/lib/python3.9/site-packages/starlette/exceptions.py\", line 71, in __call__\n    await self.app(scope, receive, sender)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/routing.py\", line 566, in __call__\n    await route.handle(scope, receive, send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/routing.py\", line 227, in handle\n    await self.app(scope, receive, send)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/routing.py\", line 41, in app\n    response = await func(request)\n  File \"/root/.local/lib/python3.9/site-packages/fastapi/routing.py\", line 182, in app\n    raw_response = await run_endpoint_function(\n  File \"/root/.local/lib/python3.9/site-packages/fastapi/routing.py\", line 135, in run_endpoint_function\n    return await run_in_threadpool(dependant.call, **values)\n  File \"/root/.local/lib/python3.9/site-packages/starlette/concurrency.py\", line 34, in run_in_threadpool\n    return await loop.run_in_executor(None, func, *args)\n  File \"/usr/local/lib/python3.9/concurrent/futures/thread.py\", line 52, in run\n    result = self.fn(*self.args, **self.kwargs)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/routers/structures.py\", line 34, in get_structures\n    return get_entries(\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/routers/utils.py\", line 196, in get_entries\n    results, data_returned, more_data_available, fields = collection.find(params)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/entry_collections/mongo.py\", line 108, in find\n    criteria = self.handle_query_params(params)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/server/entry_collections/entry_collections.py\", line 150, in handle_query_params\n    tree = self.parser.parse(params.filter)\n  File \"/root/.local/lib/python3.9/site-packages/optimade/filterparser/lark_parser.py\", line 49, in parse\n    raise ParserError(e)\noptimade.filterparser.lark_parser.ParserError: No terminal defined for '-' at line 1 ...
  ```
</details>

**Comment by CasperWA** [comment] 2020-11-05 09:12
Duplicate of #182

**Closed as completed by CasperWA** 2020-11-05 09:12 UTC
Labels: bug, duplicate
